/* eslint-disable */
// @ts-nocheck

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async greet(name: string) : Promise<GreetResponse> {
    return await TAURI_INVOKE("greet", { name });
},
async listEnvironments() : Promise<Result<Environment[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_environments") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getEnvironment(id: number) : Promise<Result<Environment | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_environment", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createEnvironment(input: NewEnvironment) : Promise<Result<Environment, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_environment", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateEnvironment(id: number, input: UpdateEnvironment) : Promise<Result<Environment | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_environment", { id, input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteEnvironment(id: number) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_environment", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listSpecies(query: string | null, sunRequirement: string | null, waterRequirement: string | null, growthType: string | null, limit: number | null, offset: number | null) : Promise<Result<Species[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_species", { query, sunRequirement, waterRequirement, growthType, limit, offset }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSpecies(id: number) : Promise<Result<Species | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_species", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createSpecies(input: NewSpecies) : Promise<Result<Species, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_species", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateSpecies(id: number, input: UpdateSpecies) : Promise<Result<Species | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_species", { id, input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteSpecies(id: number) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_species", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Search iNaturalist for taxa matching the given query.
 * Returns up to 20 results — the frontend presents them for the user to pick.
 */
async searchInaturalist(query: string) : Promise<Result<TaxonResult[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("search_inaturalist", { query }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Enrich an existing species record with data fetched from iNaturalist.
 * Uses the species' inaturalist_id if already set; otherwise falls back to
 * searching by scientific_name then common_name.
 */
async enrichSpeciesInaturalist(speciesId: number) : Promise<Result<Species, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("enrich_species_inaturalist", { speciesId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Search Wikipedia for pages matching the given query.
 */
async searchWikipedia(query: string) : Promise<Result<WikiSummary, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("search_wikipedia", { query }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Enrich an existing species record with data fetched from Wikipedia.
 * Uses the species' wikipedia_slug if already set, otherwise derives a slug
 * from scientific_name or common_name.
 */
async enrichSpeciesWikipedia(speciesId: number) : Promise<Result<Species, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("enrich_species_wikipedia", { speciesId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listPlants(environmentId: number, limit: number | null, offset: number | null) : Promise<Result<Plant[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_plants", { environmentId, limit, offset }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listAllPlants(limit: number | null, offset: number | null) : Promise<Result<Plant[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_all_plants", { limit, offset }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listPlantsBySpecies(speciesId: number, limit: number | null, offset: number | null) : Promise<Result<Plant[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_plants_by_species", { speciesId, limit, offset }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listPlantsByStatus(environmentId: number, status: PlantStatus, limit: number | null, offset: number | null) : Promise<Result<Plant[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_plants_by_status", { environmentId, status, limit, offset }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listPlantsByLocation(locationId: number, limit: number | null, offset: number | null) : Promise<Result<Plant[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_plants_by_location", { locationId, limit, offset }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getPlant(id: number) : Promise<Result<Plant | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_plant", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createPlant(input: NewPlant) : Promise<Result<Plant, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_plant", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updatePlant(id: number, input: UpdatePlant) : Promise<Result<Plant | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_plant", { id, input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deletePlant(id: number) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_plant", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changePlantStatus(id: number, status: PlantStatus) : Promise<Result<Plant | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_plant_status", { id, status }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async transitionPlantStatus(plantId: number, newStatus: PlantStatus) : Promise<Result<Plant, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("transition_plant_status", { plantId, newStatus }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listSeedlingObservations(plantId: number) : Promise<Result<SeedlingObservation[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_seedling_observations", { plantId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createSeedlingObservation(input: NewSeedlingObservation) : Promise<Result<SeedlingObservation, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_seedling_observation", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteSeedlingObservation(id: number) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_seedling_observation", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listPlantGroups(environmentId: number, limit: number | null, offset: number | null) : Promise<Result<PlantGroup[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_plant_groups", { environmentId, limit, offset }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getPlantGroup(id: number) : Promise<Result<PlantGroup | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_plant_group", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createPlantGroup(input: NewPlantGroup) : Promise<Result<PlantGroup, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_plant_group", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updatePlantGroup(id: number, input: UpdatePlantGroup) : Promise<Result<PlantGroup | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_plant_group", { id, input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deletePlantGroup(id: number) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_plant_group", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async addPlantToGroup(groupId: number, plantId: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_plant_to_group", { groupId, plantId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async removePlantFromGroup(groupId: number, plantId: number) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_plant_from_group", { groupId, plantId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listPlantGroupPlants(groupId: number) : Promise<Result<Plant[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_plant_group_plants", { groupId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listCustomFields(entityType: CustomFieldEntityType, entityId: number) : Promise<Result<CustomField[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_custom_fields", { entityType, entityId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createCustomField(input: NewCustomField) : Promise<Result<CustomField, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_custom_field", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateCustomField(id: number, input: UpdateCustomField) : Promise<Result<CustomField | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_custom_field", { id, input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteCustomField(id: number) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_custom_field", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveCanvas(environmentId: number, canvasJson: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_canvas", { environmentId, canvasJson }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async loadCanvas(environmentId: number) : Promise<Result<string | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_canvas", { environmentId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listLocations(environmentId: number) : Promise<Result<Location[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_locations", { environmentId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getLocation(id: number) : Promise<Result<Location | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_location", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createLocation(input: NewLocation) : Promise<Result<Location, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_location", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateLocation(id: number, input: UpdateLocation) : Promise<Result<Location | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_location", { id, input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteLocation(id: number) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_location", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listChildLocations(parentId: number) : Promise<Result<Location[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_child_locations", { parentId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listIssues(environmentId: number, limit: number | null, offset: number | null) : Promise<Result<Issue[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_issues", { environmentId, limit, offset }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getIssue(id: number) : Promise<Result<Issue | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_issue", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createIssue(input: NewIssue) : Promise<Result<Issue, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_issue", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateIssue(id: number, input: UpdateIssue) : Promise<Result<Issue | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_issue", { id, input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteIssue(id: number) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_issue", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async transitionIssueStatus(id: number, newStatus: IssueStatus) : Promise<Result<Issue | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("transition_issue_status", { id, newStatus }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listLabels() : Promise<Result<IssueLabel[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_labels") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createLabel(input: NewIssueLabel) : Promise<Result<IssueLabel, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_label", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateLabel(id: number, input: UpdateIssueLabel) : Promise<Result<IssueLabel | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_label", { id, input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteLabel(id: number) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_label", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listIssueLabels(issueId: number) : Promise<Result<IssueLabel[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_issue_labels", { issueId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async assignIssueLabel(issueId: number, labelId: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("assign_issue_label", { issueId, labelId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async removeIssueLabel(issueId: number, labelId: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_issue_label", { issueId, labelId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listIssueComments(issueId: number) : Promise<Result<IssueComment[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_issue_comments", { issueId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async addIssueComment(issueId: number, body: string) : Promise<Result<IssueComment, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_issue_comment", { issueId, body }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteIssueComment(id: number) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_issue_comment", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listJournalEntries(environmentId: number, plantId: number | null, limit: number | null, offset: number | null) : Promise<Result<JournalEntry[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_journal_entries", { environmentId, plantId, limit, offset }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getJournalEntry(id: number) : Promise<Result<JournalEntry | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_journal_entry", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createJournalEntry(input: NewJournalEntry) : Promise<Result<JournalEntry, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_journal_entry", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateJournalEntry(id: number, input: UpdateJournalEntry) : Promise<Result<JournalEntry | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_journal_entry", { id, input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteJournalEntry(id: number) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_journal_entry", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async uploadMedia(entityType: string, entityId: number, filePath: string) : Promise<Result<Media, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("upload_media", { entityType, entityId, filePath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listMedia(entityType: string, entityId: number) : Promise<Result<Media[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_media", { entityType, entityId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteMedia(id: number) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_media", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async readMediaBase64(id: number, thumbnail: boolean) : Promise<Result<MediaBase64, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_media_base64", { id, thumbnail }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listSchedules(environmentId: number) : Promise<Result<Schedule[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_schedules", { environmentId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSchedule(id: number) : Promise<Result<Schedule | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_schedule", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createSchedule(input: NewSchedule) : Promise<Result<Schedule, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_schedule", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateSchedule(id: number, input: UpdateSchedule) : Promise<Result<Schedule | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_schedule", { id, input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteSchedule(id: number) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_schedule", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async toggleSchedule(id: number, active: boolean) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("toggle_schedule", { id, active }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listScheduleRuns(scheduleId: number, limit: number | null) : Promise<Result<ScheduleRun[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_schedule_runs", { scheduleId, limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getCalendarEvents(environmentId: number, startDate: string, endDate: string) : Promise<Result<CalendarEvent[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_calendar_events", { environmentId, startDate, endDate }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listAdditives() : Promise<Result<Additive[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_additives") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getScheduleSuggestions(plantId: number) : Promise<Result<ScheduleSuggestion[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_schedule_suggestions", { plantId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getWeather(environmentId: number) : Promise<Result<WeatherData | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_weather", { environmentId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async refreshWeather(environmentId: number) : Promise<Result<WeatherData | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("refresh_weather", { environmentId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getWeatherApiKey() : Promise<Result<string | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_weather_api_key") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setWeatherApiKey(apiKey: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_weather_api_key", { apiKey }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listSensors(environmentId: number, limit?: number | null, offset?: number | null) : Promise<Result<Sensor[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_sensors", { environmentId, limit, offset }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSensor(id: number) : Promise<Result<Sensor | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_sensor", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createSensor(input: NewSensor) : Promise<Result<Sensor, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_sensor", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateSensor(id: number, input: UpdateSensor) : Promise<Result<Sensor | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_sensor", { id, input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteSensor(id: number) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_sensor", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async startSensor(id: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_sensor", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async stopSensor(id: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_sensor", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listSensorReadings(sensorId: number, limit?: number | null, offset?: number | null) : Promise<Result<SensorReading[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_sensor_readings", { sensorId, limit, offset }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getLatestReading(sensorId: number) : Promise<Result<SensorReading | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_latest_reading", { sensorId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async recordManualReading(sensorId: number, value: number, unit?: string | null) : Promise<Result<SensorReading, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("record_manual_reading", { sensorId, value, unit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSensorLimits(sensorId: number) : Promise<Result<SensorLimit | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_sensor_limits", { sensorId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setSensorLimits(sensorId: number, minValue: number | null, maxValue: number | null, unit: string | null, alertEnabled: boolean) : Promise<Result<SensorLimit, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_sensor_limits", { sensorId, minValue, maxValue, unit, alertEnabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createSoilTest(input: NewSoilTest) : Promise<Result<SoilTest, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_soil_test", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listSoilTests(locationId: number) : Promise<Result<SoilTest[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_soil_tests", { locationId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteSoilTest(id: number) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_soil_test", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type Additive = { id: number; name: string; additive_type: AdditiveType; npk_n: number | null; npk_p: number | null; npk_k: number | null; application_rate: number | null; application_unit: string | null; notes: string | null }
export type AdditiveType = "fertilizer" | "amendment" | "pesticide" | "fungicide" | "other"
export type CalendarEvent = { id: string; event_type: CalendarEventType; date: string; title: string; color: string | null; plant_id: number | null; schedule_id: number | null; issue_id: number | null }
export type CalendarEventType = "Schedule" | "PlantingDate" | "HarvestDate" | "IssueCreated"
export type CustomField = { id: number; entity_type: CustomFieldEntityType; entity_id: number; field_name: string; field_value: string | null; field_type: CustomFieldType; created_at: string }
export type CustomFieldEntityType = "Species" | "Plant" | "Location" | "SoilTest"
export type CustomFieldType = "Text" | "Number" | "Date" | "Boolean"
export type Environment = { id: number; name: string; latitude: number | null; longitude: number | null; elevation_m: number | null; timezone: string | null; climate_zone: string | null; created_at: string; updated_at: string }
/**
 * Temporary smoke-test command to verify IPC and specta type export.
 * This command will be removed after Phase 0 verification.
 */
export type GreetResponse = { message: string }
export type Issue = { id: number; environment_id: number | null; plant_id: number | null; location_id: number | null; title: string; description: string | null; status: IssueStatus; priority: IssuePriority; created_at: string; updated_at: string; closed_at: string | null }
export type IssueComment = { id: number; issue_id: number; body: string; created_at: string }
export type IssueLabel = { id: number; name: string; color: string | null; icon: string | null }
export type IssuePriority = "low" | "medium" | "high" | "critical"
export type IssueStatus = "new" | "open" | "in_progress" | "closed"
export type JournalEntry = { id: number; environment_id: number | null; plant_id: number | null; location_id: number | null; title: string; body: string | null; conditions_json: string | null; created_at: string; updated_at: string }
export type Location = { id: number; environment_id: number; parent_id: number | null; location_type: LocationType; name: string; label: string | null; position_x: number | null; position_y: number | null; width: number | null; height: number | null; canvas_data_json: string | null; notes: string | null; created_at: string; updated_at: string }
export type LocationType = "Plot" | "Space" | "Tent" | "Tray" | "Pot" | "Shed"
export type Media = { id: number; entity_type: string; entity_id: number; file_path: string; file_name: string; mime_type: string | null; thumbnail_path: string | null; caption: string | null; created_at: string }
export type MediaBase64 = { id: number; mime_type: string; data: string; is_thumbnail: boolean }
export type NewCustomField = { entity_type: CustomFieldEntityType; entity_id: number; field_name: string; field_value: string | null; field_type: CustomFieldType }
export type NewEnvironment = { name: string; latitude: number | null; longitude: number | null; elevation_m: number | null; timezone: string | null; climate_zone: string | null }
export type NewIssue = { environment_id: number | null; plant_id: number | null; location_id: number | null; title: string; description: string | null; status: IssueStatus | null; priority: IssuePriority | null }
export type NewIssueLabel = { name: string; color: string | null; icon: string | null }
export type NewJournalEntry = { environment_id: number | null; plant_id: number | null; location_id: number | null; title: string; body: string | null; conditions_json: string | null }
export type NewLocation = { environment_id: number; parent_id: number | null; location_type: LocationType; name: string; label: string | null; position_x: number | null; position_y: number | null; width: number | null; height: number | null; canvas_data_json: string | null; notes: string | null }
export type NewSchedule = { environment_id: number | null; plant_id: number | null; location_id: number | null; schedule_type: ScheduleType; title: string; cron_expression: string | null; next_run_at: string | null; is_active: boolean | null; additive_id: number | null; notes: string | null }
export type NewPlant = { species_id: number | null; location_id: number | null; environment_id: number; status: PlantStatus | null; name: string; label: string | null; planted_date: string | null; notes: string | null }
export type NewPlantGroup = { environment_id: number; name: string; description: string | null; group_type: string | null; color: string | null }
export type NewSeedlingObservation = { plant_id: number; observed_at: string | null; height_cm: number | null; stem_thickness_mm: number | null; leaf_node_count: number | null; leaf_node_spacing_mm: number | null; notes: string | null }
export type NewSpecies = { common_name: string; scientific_name: string | null; family: string | null; genus: string | null; growth_type: string | null; sun_requirement: string | null; water_requirement: string | null; soil_ph_min: number | null; soil_ph_max: number | null; spacing_cm: number | null; days_to_germination_min: number | null; days_to_germination_max: number | null; days_to_harvest_min: number | null; days_to_harvest_max: number | null; hardiness_zone_min: string | null; hardiness_zone_max: string | null; description: string | null; image_url: string | null; is_user_added: boolean | null }
export type Plant = { id: number; species_id: number | null; location_id: number | null; environment_id: number; status: PlantStatus; name: string; label: string | null; planted_date: string | null; germinated_date: string | null; transplanted_date: string | null; removed_date: string | null; parent_plant_id: number | null; seed_lot_id: number | null; purchase_source: string | null; purchase_date: string | null; purchase_price: number | null; notes: string | null; created_at: string; updated_at: string }
export type PlantGroup = { id: number; environment_id: number; name: string; description: string | null; group_type: string | null; filter_criteria_json: string | null; color: string | null; created_at: string; updated_at: string }
export type PlantStatus = "planned" | "seedling" | "active" | "harvested" | "removed" | "dead"
export type SeedlingObservation = { id: number; plant_id: number; observed_at: string; height_cm: number | null; stem_thickness_mm: number | null; leaf_node_count: number | null; leaf_node_spacing_mm: number | null; notes: string | null; created_at: string }
export type Schedule = { id: number; environment_id: number | null; plant_id: number | null; location_id: number | null; schedule_type: ScheduleType; title: string; cron_expression: string | null; next_run_at: string | null; is_active: boolean; additive_id: number | null; notes: string | null; created_at: string; updated_at: string }
export type ScheduleRun = { id: number; schedule_id: number; issue_id: number | null; ran_at: string; status: ScheduleRunStatus }
export type ScheduleRunStatus = "completed" | "skipped" | "missed"
export type ScheduleSuggestion = { schedule_type: ScheduleType; title: string; cron_expression: string; cron_label: string; notes: string | null }
export type ScheduleType = "water" | "feed" | "maintenance" | "treatment" | "sample" | "custom"
export type Species = { id: number; common_name: string; scientific_name: string | null; family: string | null; genus: string | null; inaturalist_id: number | null; wikipedia_slug: string | null; growth_type: string | null; sun_requirement: string | null; water_requirement: string | null; soil_ph_min: number | null; soil_ph_max: number | null; spacing_cm: number | null; days_to_germination_min: number | null; days_to_germination_max: number | null; days_to_harvest_min: number | null; days_to_harvest_max: number | null; hardiness_zone_min: string | null; hardiness_zone_max: string | null; description: string | null; image_url: string | null; cached_inaturalist_json: string | null; cached_wikipedia_json: string | null; is_user_added: boolean; created_at: string; updated_at: string }
export type TaxonResult = { id: number; name: string; preferred_common_name: string | null; rank: string | null; default_photo_url: string | null; wikipedia_url: string | null; matched_term: string | null }
export type UpdateCustomField = { field_name: string | null; field_value: string | null; field_type: CustomFieldType | null }
export type UpdateEnvironment = { name: string | null; latitude: number | null; longitude: number | null; elevation_m: number | null; timezone: string | null; climate_zone: string | null }
export type UpdateIssue = { title: string | null; description: string | null; status: IssueStatus | null; priority: IssuePriority | null; plant_id: number | null; location_id: number | null }
export type UpdateIssueLabel = { name: string | null; color: string | null; icon: string | null }
export type UpdateJournalEntry = { title: string | null; body: string | null; conditions_json: string | null }
export type UpdateSchedule = { schedule_type: ScheduleType | null; title: string | null; cron_expression: string | null; is_active: boolean | null; plant_id: number | null; location_id: number | null; additive_id: number | null; notes: string | null }
export type UpdateLocation = { parent_id: number | null; location_type: LocationType | null; name: string | null; label: string | null; position_x: number | null; position_y: number | null; width: number | null; height: number | null; canvas_data_json: string | null; notes: string | null }
export type UpdatePlant = { species_id: number | null; location_id: number | null; status: PlantStatus | null; name: string | null; label: string | null; planted_date: string | null; germinated_date: string | null; transplanted_date: string | null; removed_date: string | null; parent_plant_id: number | null; seed_lot_id: number | null; purchase_source: string | null; purchase_date: string | null; purchase_price: number | null; notes: string | null }
export type UpdatePlantGroup = { name: string | null; description: string | null; group_type: string | null; color: string | null }
export type UpdateSpecies = { common_name: string | null; scientific_name: string | null; family: string | null; genus: string | null; growth_type: string | null; sun_requirement: string | null; water_requirement: string | null; soil_ph_min: number | null; soil_ph_max: number | null; spacing_cm: number | null; days_to_germination_min: number | null; days_to_germination_max: number | null; days_to_harvest_min: number | null; days_to_harvest_max: number | null; hardiness_zone_min: string | null; hardiness_zone_max: string | null; description: string | null; image_url: string | null }
export type WikiSummary = { title: string; slug: string; extract: string | null; thumbnail_url: string | null; page_url: string | null; raw_json: string }
export type CurrentWeather = { temperature_c: number; feels_like_c: number; humidity: number; pressure_hpa: number; wind_speed_ms: number; wind_direction_deg: number; cloud_cover_pct: number; description: string; icon: string; sunrise: number | null; sunset: number | null; dt: number }
export type ForecastItem = { dt: number; temperature_c: number; feels_like_c: number; humidity: number; wind_speed_ms: number; cloud_cover_pct: number; precipitation_mm: number | null; precipitation_prob: number | null; description: string; icon: string }
export type DailyForecast = { date: string; temp_min_c: number; temp_max_c: number; description: string; icon: string; precipitation_mm: number | null; precipitation_prob: number | null }
export type WeatherData = { current: CurrentWeather; hourly: ForecastItem[]; daily: DailyForecast[]; from_cache: boolean; fetched_at: string }
export type Sensor = { id: number; environment_id: number | null; location_id: number | null; plant_id: number | null; name: string; sensor_type: SensorType; connection_type: SensorConnectionType; connection_config_json: string | null; poll_interval_seconds: number | null; is_active: boolean; created_at: string; updated_at: string }
export type SensorType = "moisture" | "light" | "temperature" | "humidity" | "ph" | "ec" | "co2" | "air_quality" | "custom"
export type SensorConnectionType = "serial" | "usb" | "mqtt" | "http" | "manual"
export type NewSensor = { environment_id: number | null; location_id: number | null; plant_id: number | null; name: string; sensor_type: SensorType; connection_type: SensorConnectionType; connection_config_json: string | null; poll_interval_seconds: number | null; is_active: boolean | null }
export type UpdateSensor = { name: string | null; sensor_type: SensorType | null; connection_type: SensorConnectionType | null; connection_config_json: string | null; poll_interval_seconds: number | null; location_id: number | null; plant_id: number | null; is_active: boolean | null }
export type SensorReading = { id: number; sensor_id: number; value: number; unit: string | null; recorded_at: string }
export type SensorLimit = { id: number; sensor_id: number; min_value: number | null; max_value: number | null; unit: string | null; alert_enabled: boolean }
export type SoilTest = { id: number; location_id: number; test_date: string; ph: number | null; nitrogen_ppm: number | null; phosphorus_ppm: number | null; potassium_ppm: number | null; moisture_pct: number | null; organic_matter_pct: number | null; notes: string | null; created_at: string }
export type NewSoilTest = { location_id: number; test_date: string; ph: number | null; nitrogen_ppm: number | null; phosphorus_ppm: number | null; potassium_ppm: number | null; moisture_pct: number | null; organic_matter_pct: number | null; notes: string | null }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
