-- Phase 6: Issue Tracker — seed default issue labels.

INSERT OR IGNORE INTO issue_labels (name, color, icon) VALUES
  ('Insect Damage',      '#FF6B35', 'bug'),
  ('Aphids',             '#FF6B35', 'bug'),
  ('Spider Mites',       '#FF6B35', 'bug'),
  ('Caterpillar',        '#FF6B35', 'bug'),
  ('Whitefly',           '#FF6B35', 'bug'),
  ('Fungal Disease',     '#9C89B8', 'leaf-off'),
  ('Powdery Mildew',     '#9C89B8', 'leaf-off'),
  ('Blight',             '#9C89B8', 'leaf-off'),
  ('Root Rot',           '#6B4226', 'plant'),
  ('Damping Off',        '#6B4226', 'plant'),
  ('Bacterial Disease',  '#C05C7E', 'flask'),
  ('Nutrient Deficiency','#F4A261', 'exclamation'),
  ('Nitrogen Deficiency','#F4A261', 'exclamation'),
  ('Iron Deficiency',    '#F4A261', 'exclamation'),
  ('Overwatering',       '#4EA8DE', 'droplet-slash'),
  ('Underwatering',      '#E76F51', 'droplet'),
  ('Heat Stress',        '#E9C46A', 'sun'),
  ('Cold Damage',        '#90E0EF', 'snowflake'),
  ('Wind Damage',        '#ADB5BD', 'wind'),
  ('Mechanical Damage',  '#ADB5BD', 'scissors'),
  ('Leggy / Etiolated',  '#F4A261', 'arrow-up'),
  ('Poor Germination',   '#6C757D', 'seed'),
  ('Transplant Shock',   '#20C997', 'arrows-shuffle'),
  ('Wilting',            '#FFC300', 'activity'),
  ('Yellowing Leaves',   '#FFC300', 'leaf'),
  ('Browning Tips',      '#A0522D', 'leaf'),
  ('Pest — General',     '#FF6B35', 'bug'),
  ('Weed Pressure',      '#55A630', 'spa'),
  ('Animal Damage',      '#8B4513', 'paw-print'),
  ('Healthy — Monitor',  '#52B788', 'check-circle'),
  ('Maintenance',        '#74C0FC', 'tool'),
  ('Feeding',            '#A9E34B', 'droplet-filled'),
  ('Treatment',          '#F783AC', 'pill'),
  ('Watering Issue',     '#4EA8DE', 'droplet');
