/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WeatherRouteImport } from './routes/weather'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SensorsRouteImport } from './routes/sensors'
import { Route as SchedulesRouteImport } from './routes/schedules'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PlantsRouteImport } from './routes/plants'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as IssuesRouteImport } from './routes/issues'
import { Route as IndoorRouteImport } from './routes/indoor'
import { Route as GardenRouteImport } from './routes/garden'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SchedulesIndexRouteImport } from './routes/schedules.index'
import { Route as PlantsIndexRouteImport } from './routes/plants.index'
import { Route as JournalIndexRouteImport } from './routes/journal.index'
import { Route as IssuesIndexRouteImport } from './routes/issues.index'
import { Route as IndoorIndexRouteImport } from './routes/indoor.index'
import { Route as GardenIndexRouteImport } from './routes/garden.index'
import { Route as PlantsTraysRouteImport } from './routes/plants.trays'
import { Route as PlantsSeedsRouteImport } from './routes/plants.seeds'
import { Route as PlantsSeedlingsRouteImport } from './routes/plants.seedlings'
import { Route as PlantsIndividualsRouteImport } from './routes/plants.individuals'
import { Route as PlantsGroupsRouteImport } from './routes/plants.groups'
import { Route as PlantsSpeciesIdRouteImport } from './routes/plants.$speciesId'
import { Route as JournalEntryIdRouteImport } from './routes/journal.$entryId'
import { Route as IssuesIssueIdRouteImport } from './routes/issues.$issueId'
import { Route as IndoorEnvironmentIdRouteImport } from './routes/indoor.$environmentId'
import { Route as GardenLocationIdRouteImport } from './routes/garden.$locationId'
import { Route as PlantsIndividualsIndexRouteImport } from './routes/plants.individuals.index'
import { Route as PlantsIndividualsPlantIdRouteImport } from './routes/plants.individuals.$plantId'

const WeatherRoute = WeatherRouteImport.update({
  id: '/weather',
  path: '/weather',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SensorsRoute = SensorsRouteImport.update({
  id: '/sensors',
  path: '/sensors',
  getParentRoute: () => rootRouteImport,
} as any)
const SchedulesRoute = SchedulesRouteImport.update({
  id: '/schedules',
  path: '/schedules',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PlantsRoute = PlantsRouteImport.update({
  id: '/plants',
  path: '/plants',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const IssuesRoute = IssuesRouteImport.update({
  id: '/issues',
  path: '/issues',
  getParentRoute: () => rootRouteImport,
} as any)
const IndoorRoute = IndoorRouteImport.update({
  id: '/indoor',
  path: '/indoor',
  getParentRoute: () => rootRouteImport,
} as any)
const GardenRoute = GardenRouteImport.update({
  id: '/garden',
  path: '/garden',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SchedulesIndexRoute = SchedulesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SchedulesRoute,
} as any)
const PlantsIndexRoute = PlantsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PlantsRoute,
} as any)
const JournalIndexRoute = JournalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => JournalRoute,
} as any)
const IssuesIndexRoute = IssuesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => IssuesRoute,
} as any)
const IndoorIndexRoute = IndoorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => IndoorRoute,
} as any)
const GardenIndexRoute = GardenIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GardenRoute,
} as any)
const PlantsTraysRoute = PlantsTraysRouteImport.update({
  id: '/trays',
  path: '/trays',
  getParentRoute: () => PlantsRoute,
} as any)
const PlantsSeedsRoute = PlantsSeedsRouteImport.update({
  id: '/seeds',
  path: '/seeds',
  getParentRoute: () => PlantsRoute,
} as any)
const PlantsSeedlingsRoute = PlantsSeedlingsRouteImport.update({
  id: '/seedlings',
  path: '/seedlings',
  getParentRoute: () => PlantsRoute,
} as any)
const PlantsIndividualsRoute = PlantsIndividualsRouteImport.update({
  id: '/individuals',
  path: '/individuals',
  getParentRoute: () => PlantsRoute,
} as any)
const PlantsGroupsRoute = PlantsGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => PlantsRoute,
} as any)
const PlantsSpeciesIdRoute = PlantsSpeciesIdRouteImport.update({
  id: '/$speciesId',
  path: '/$speciesId',
  getParentRoute: () => PlantsRoute,
} as any)
const JournalEntryIdRoute = JournalEntryIdRouteImport.update({
  id: '/$entryId',
  path: '/$entryId',
  getParentRoute: () => JournalRoute,
} as any)
const IssuesIssueIdRoute = IssuesIssueIdRouteImport.update({
  id: '/$issueId',
  path: '/$issueId',
  getParentRoute: () => IssuesRoute,
} as any)
const IndoorEnvironmentIdRoute = IndoorEnvironmentIdRouteImport.update({
  id: '/$environmentId',
  path: '/$environmentId',
  getParentRoute: () => IndoorRoute,
} as any)
const GardenLocationIdRoute = GardenLocationIdRouteImport.update({
  id: '/$locationId',
  path: '/$locationId',
  getParentRoute: () => GardenRoute,
} as any)
const PlantsIndividualsIndexRoute = PlantsIndividualsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PlantsIndividualsRoute,
} as any)
const PlantsIndividualsPlantIdRoute =
  PlantsIndividualsPlantIdRouteImport.update({
    id: '/$plantId',
    path: '/$plantId',
    getParentRoute: () => PlantsIndividualsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/garden': typeof GardenRouteWithChildren
  '/indoor': typeof IndoorRouteWithChildren
  '/issues': typeof IssuesRouteWithChildren
  '/journal': typeof JournalRouteWithChildren
  '/plants': typeof PlantsRouteWithChildren
  '/reports': typeof ReportsRoute
  '/schedules': typeof SchedulesRouteWithChildren
  '/sensors': typeof SensorsRoute
  '/settings': typeof SettingsRoute
  '/weather': typeof WeatherRoute
  '/garden/$locationId': typeof GardenLocationIdRoute
  '/indoor/$environmentId': typeof IndoorEnvironmentIdRoute
  '/issues/$issueId': typeof IssuesIssueIdRoute
  '/journal/$entryId': typeof JournalEntryIdRoute
  '/plants/$speciesId': typeof PlantsSpeciesIdRoute
  '/plants/groups': typeof PlantsGroupsRoute
  '/plants/individuals': typeof PlantsIndividualsRouteWithChildren
  '/plants/seedlings': typeof PlantsSeedlingsRoute
  '/plants/seeds': typeof PlantsSeedsRoute
  '/plants/trays': typeof PlantsTraysRoute
  '/garden/': typeof GardenIndexRoute
  '/indoor/': typeof IndoorIndexRoute
  '/issues/': typeof IssuesIndexRoute
  '/journal/': typeof JournalIndexRoute
  '/plants/': typeof PlantsIndexRoute
  '/schedules/': typeof SchedulesIndexRoute
  '/plants/individuals/$plantId': typeof PlantsIndividualsPlantIdRoute
  '/plants/individuals/': typeof PlantsIndividualsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/reports': typeof ReportsRoute
  '/sensors': typeof SensorsRoute
  '/settings': typeof SettingsRoute
  '/weather': typeof WeatherRoute
  '/garden/$locationId': typeof GardenLocationIdRoute
  '/indoor/$environmentId': typeof IndoorEnvironmentIdRoute
  '/issues/$issueId': typeof IssuesIssueIdRoute
  '/journal/$entryId': typeof JournalEntryIdRoute
  '/plants/$speciesId': typeof PlantsSpeciesIdRoute
  '/plants/groups': typeof PlantsGroupsRoute
  '/plants/seedlings': typeof PlantsSeedlingsRoute
  '/plants/seeds': typeof PlantsSeedsRoute
  '/plants/trays': typeof PlantsTraysRoute
  '/garden': typeof GardenIndexRoute
  '/indoor': typeof IndoorIndexRoute
  '/issues': typeof IssuesIndexRoute
  '/journal': typeof JournalIndexRoute
  '/plants': typeof PlantsIndexRoute
  '/schedules': typeof SchedulesIndexRoute
  '/plants/individuals/$plantId': typeof PlantsIndividualsPlantIdRoute
  '/plants/individuals': typeof PlantsIndividualsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/garden': typeof GardenRouteWithChildren
  '/indoor': typeof IndoorRouteWithChildren
  '/issues': typeof IssuesRouteWithChildren
  '/journal': typeof JournalRouteWithChildren
  '/plants': typeof PlantsRouteWithChildren
  '/reports': typeof ReportsRoute
  '/schedules': typeof SchedulesRouteWithChildren
  '/sensors': typeof SensorsRoute
  '/settings': typeof SettingsRoute
  '/weather': typeof WeatherRoute
  '/garden/$locationId': typeof GardenLocationIdRoute
  '/indoor/$environmentId': typeof IndoorEnvironmentIdRoute
  '/issues/$issueId': typeof IssuesIssueIdRoute
  '/journal/$entryId': typeof JournalEntryIdRoute
  '/plants/$speciesId': typeof PlantsSpeciesIdRoute
  '/plants/groups': typeof PlantsGroupsRoute
  '/plants/individuals': typeof PlantsIndividualsRouteWithChildren
  '/plants/seedlings': typeof PlantsSeedlingsRoute
  '/plants/seeds': typeof PlantsSeedsRoute
  '/plants/trays': typeof PlantsTraysRoute
  '/garden/': typeof GardenIndexRoute
  '/indoor/': typeof IndoorIndexRoute
  '/issues/': typeof IssuesIndexRoute
  '/journal/': typeof JournalIndexRoute
  '/plants/': typeof PlantsIndexRoute
  '/schedules/': typeof SchedulesIndexRoute
  '/plants/individuals/$plantId': typeof PlantsIndividualsPlantIdRoute
  '/plants/individuals/': typeof PlantsIndividualsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/garden'
    | '/indoor'
    | '/issues'
    | '/journal'
    | '/plants'
    | '/reports'
    | '/schedules'
    | '/sensors'
    | '/settings'
    | '/weather'
    | '/garden/$locationId'
    | '/indoor/$environmentId'
    | '/issues/$issueId'
    | '/journal/$entryId'
    | '/plants/$speciesId'
    | '/plants/groups'
    | '/plants/individuals'
    | '/plants/seedlings'
    | '/plants/seeds'
    | '/plants/trays'
    | '/garden/'
    | '/indoor/'
    | '/issues/'
    | '/journal/'
    | '/plants/'
    | '/schedules/'
    | '/plants/individuals/$plantId'
    | '/plants/individuals/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/reports'
    | '/sensors'
    | '/settings'
    | '/weather'
    | '/garden/$locationId'
    | '/indoor/$environmentId'
    | '/issues/$issueId'
    | '/journal/$entryId'
    | '/plants/$speciesId'
    | '/plants/groups'
    | '/plants/seedlings'
    | '/plants/seeds'
    | '/plants/trays'
    | '/garden'
    | '/indoor'
    | '/issues'
    | '/journal'
    | '/plants'
    | '/schedules'
    | '/plants/individuals/$plantId'
    | '/plants/individuals'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/garden'
    | '/indoor'
    | '/issues'
    | '/journal'
    | '/plants'
    | '/reports'
    | '/schedules'
    | '/sensors'
    | '/settings'
    | '/weather'
    | '/garden/$locationId'
    | '/indoor/$environmentId'
    | '/issues/$issueId'
    | '/journal/$entryId'
    | '/plants/$speciesId'
    | '/plants/groups'
    | '/plants/individuals'
    | '/plants/seedlings'
    | '/plants/seeds'
    | '/plants/trays'
    | '/garden/'
    | '/indoor/'
    | '/issues/'
    | '/journal/'
    | '/plants/'
    | '/schedules/'
    | '/plants/individuals/$plantId'
    | '/plants/individuals/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  GardenRoute: typeof GardenRouteWithChildren
  IndoorRoute: typeof IndoorRouteWithChildren
  IssuesRoute: typeof IssuesRouteWithChildren
  JournalRoute: typeof JournalRouteWithChildren
  PlantsRoute: typeof PlantsRouteWithChildren
  ReportsRoute: typeof ReportsRoute
  SchedulesRoute: typeof SchedulesRouteWithChildren
  SensorsRoute: typeof SensorsRoute
  SettingsRoute: typeof SettingsRoute
  WeatherRoute: typeof WeatherRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/weather': {
      id: '/weather'
      path: '/weather'
      fullPath: '/weather'
      preLoaderRoute: typeof WeatherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sensors': {
      id: '/sensors'
      path: '/sensors'
      fullPath: '/sensors'
      preLoaderRoute: typeof SensorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedules': {
      id: '/schedules'
      path: '/schedules'
      fullPath: '/schedules'
      preLoaderRoute: typeof SchedulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plants': {
      id: '/plants'
      path: '/plants'
      fullPath: '/plants'
      preLoaderRoute: typeof PlantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/issues': {
      id: '/issues'
      path: '/issues'
      fullPath: '/issues'
      preLoaderRoute: typeof IssuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/indoor': {
      id: '/indoor'
      path: '/indoor'
      fullPath: '/indoor'
      preLoaderRoute: typeof IndoorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/garden': {
      id: '/garden'
      path: '/garden'
      fullPath: '/garden'
      preLoaderRoute: typeof GardenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedules/': {
      id: '/schedules/'
      path: '/'
      fullPath: '/schedules/'
      preLoaderRoute: typeof SchedulesIndexRouteImport
      parentRoute: typeof SchedulesRoute
    }
    '/plants/': {
      id: '/plants/'
      path: '/'
      fullPath: '/plants/'
      preLoaderRoute: typeof PlantsIndexRouteImport
      parentRoute: typeof PlantsRoute
    }
    '/journal/': {
      id: '/journal/'
      path: '/'
      fullPath: '/journal/'
      preLoaderRoute: typeof JournalIndexRouteImport
      parentRoute: typeof JournalRoute
    }
    '/issues/': {
      id: '/issues/'
      path: '/'
      fullPath: '/issues/'
      preLoaderRoute: typeof IssuesIndexRouteImport
      parentRoute: typeof IssuesRoute
    }
    '/indoor/': {
      id: '/indoor/'
      path: '/'
      fullPath: '/indoor/'
      preLoaderRoute: typeof IndoorIndexRouteImport
      parentRoute: typeof IndoorRoute
    }
    '/garden/': {
      id: '/garden/'
      path: '/'
      fullPath: '/garden/'
      preLoaderRoute: typeof GardenIndexRouteImport
      parentRoute: typeof GardenRoute
    }
    '/plants/trays': {
      id: '/plants/trays'
      path: '/trays'
      fullPath: '/plants/trays'
      preLoaderRoute: typeof PlantsTraysRouteImport
      parentRoute: typeof PlantsRoute
    }
    '/plants/seeds': {
      id: '/plants/seeds'
      path: '/seeds'
      fullPath: '/plants/seeds'
      preLoaderRoute: typeof PlantsSeedsRouteImport
      parentRoute: typeof PlantsRoute
    }
    '/plants/seedlings': {
      id: '/plants/seedlings'
      path: '/seedlings'
      fullPath: '/plants/seedlings'
      preLoaderRoute: typeof PlantsSeedlingsRouteImport
      parentRoute: typeof PlantsRoute
    }
    '/plants/individuals': {
      id: '/plants/individuals'
      path: '/individuals'
      fullPath: '/plants/individuals'
      preLoaderRoute: typeof PlantsIndividualsRouteImport
      parentRoute: typeof PlantsRoute
    }
    '/plants/groups': {
      id: '/plants/groups'
      path: '/groups'
      fullPath: '/plants/groups'
      preLoaderRoute: typeof PlantsGroupsRouteImport
      parentRoute: typeof PlantsRoute
    }
    '/plants/$speciesId': {
      id: '/plants/$speciesId'
      path: '/$speciesId'
      fullPath: '/plants/$speciesId'
      preLoaderRoute: typeof PlantsSpeciesIdRouteImport
      parentRoute: typeof PlantsRoute
    }
    '/journal/$entryId': {
      id: '/journal/$entryId'
      path: '/$entryId'
      fullPath: '/journal/$entryId'
      preLoaderRoute: typeof JournalEntryIdRouteImport
      parentRoute: typeof JournalRoute
    }
    '/issues/$issueId': {
      id: '/issues/$issueId'
      path: '/$issueId'
      fullPath: '/issues/$issueId'
      preLoaderRoute: typeof IssuesIssueIdRouteImport
      parentRoute: typeof IssuesRoute
    }
    '/indoor/$environmentId': {
      id: '/indoor/$environmentId'
      path: '/$environmentId'
      fullPath: '/indoor/$environmentId'
      preLoaderRoute: typeof IndoorEnvironmentIdRouteImport
      parentRoute: typeof IndoorRoute
    }
    '/garden/$locationId': {
      id: '/garden/$locationId'
      path: '/$locationId'
      fullPath: '/garden/$locationId'
      preLoaderRoute: typeof GardenLocationIdRouteImport
      parentRoute: typeof GardenRoute
    }
    '/plants/individuals/': {
      id: '/plants/individuals/'
      path: '/'
      fullPath: '/plants/individuals/'
      preLoaderRoute: typeof PlantsIndividualsIndexRouteImport
      parentRoute: typeof PlantsIndividualsRoute
    }
    '/plants/individuals/$plantId': {
      id: '/plants/individuals/$plantId'
      path: '/$plantId'
      fullPath: '/plants/individuals/$plantId'
      preLoaderRoute: typeof PlantsIndividualsPlantIdRouteImport
      parentRoute: typeof PlantsIndividualsRoute
    }
  }
}

interface GardenRouteChildren {
  GardenLocationIdRoute: typeof GardenLocationIdRoute
  GardenIndexRoute: typeof GardenIndexRoute
}

const GardenRouteChildren: GardenRouteChildren = {
  GardenLocationIdRoute: GardenLocationIdRoute,
  GardenIndexRoute: GardenIndexRoute,
}

const GardenRouteWithChildren =
  GardenRoute._addFileChildren(GardenRouteChildren)

interface IndoorRouteChildren {
  IndoorEnvironmentIdRoute: typeof IndoorEnvironmentIdRoute
  IndoorIndexRoute: typeof IndoorIndexRoute
}

const IndoorRouteChildren: IndoorRouteChildren = {
  IndoorEnvironmentIdRoute: IndoorEnvironmentIdRoute,
  IndoorIndexRoute: IndoorIndexRoute,
}

const IndoorRouteWithChildren =
  IndoorRoute._addFileChildren(IndoorRouteChildren)

interface IssuesRouteChildren {
  IssuesIssueIdRoute: typeof IssuesIssueIdRoute
  IssuesIndexRoute: typeof IssuesIndexRoute
}

const IssuesRouteChildren: IssuesRouteChildren = {
  IssuesIssueIdRoute: IssuesIssueIdRoute,
  IssuesIndexRoute: IssuesIndexRoute,
}

const IssuesRouteWithChildren =
  IssuesRoute._addFileChildren(IssuesRouteChildren)

interface JournalRouteChildren {
  JournalEntryIdRoute: typeof JournalEntryIdRoute
  JournalIndexRoute: typeof JournalIndexRoute
}

const JournalRouteChildren: JournalRouteChildren = {
  JournalEntryIdRoute: JournalEntryIdRoute,
  JournalIndexRoute: JournalIndexRoute,
}

const JournalRouteWithChildren =
  JournalRoute._addFileChildren(JournalRouteChildren)

interface PlantsIndividualsRouteChildren {
  PlantsIndividualsPlantIdRoute: typeof PlantsIndividualsPlantIdRoute
  PlantsIndividualsIndexRoute: typeof PlantsIndividualsIndexRoute
}

const PlantsIndividualsRouteChildren: PlantsIndividualsRouteChildren = {
  PlantsIndividualsPlantIdRoute: PlantsIndividualsPlantIdRoute,
  PlantsIndividualsIndexRoute: PlantsIndividualsIndexRoute,
}

const PlantsIndividualsRouteWithChildren =
  PlantsIndividualsRoute._addFileChildren(PlantsIndividualsRouteChildren)

interface PlantsRouteChildren {
  PlantsSpeciesIdRoute: typeof PlantsSpeciesIdRoute
  PlantsGroupsRoute: typeof PlantsGroupsRoute
  PlantsIndividualsRoute: typeof PlantsIndividualsRouteWithChildren
  PlantsSeedlingsRoute: typeof PlantsSeedlingsRoute
  PlantsSeedsRoute: typeof PlantsSeedsRoute
  PlantsTraysRoute: typeof PlantsTraysRoute
  PlantsIndexRoute: typeof PlantsIndexRoute
}

const PlantsRouteChildren: PlantsRouteChildren = {
  PlantsSpeciesIdRoute: PlantsSpeciesIdRoute,
  PlantsGroupsRoute: PlantsGroupsRoute,
  PlantsIndividualsRoute: PlantsIndividualsRouteWithChildren,
  PlantsSeedlingsRoute: PlantsSeedlingsRoute,
  PlantsSeedsRoute: PlantsSeedsRoute,
  PlantsTraysRoute: PlantsTraysRoute,
  PlantsIndexRoute: PlantsIndexRoute,
}

const PlantsRouteWithChildren =
  PlantsRoute._addFileChildren(PlantsRouteChildren)

interface SchedulesRouteChildren {
  SchedulesIndexRoute: typeof SchedulesIndexRoute
}

const SchedulesRouteChildren: SchedulesRouteChildren = {
  SchedulesIndexRoute: SchedulesIndexRoute,
}

const SchedulesRouteWithChildren = SchedulesRoute._addFileChildren(
  SchedulesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  GardenRoute: GardenRouteWithChildren,
  IndoorRoute: IndoorRouteWithChildren,
  IssuesRoute: IssuesRouteWithChildren,
  JournalRoute: JournalRouteWithChildren,
  PlantsRoute: PlantsRouteWithChildren,
  ReportsRoute: ReportsRoute,
  SchedulesRoute: SchedulesRouteWithChildren,
  SensorsRoute: SensorsRoute,
  SettingsRoute: SettingsRoute,
  WeatherRoute: WeatherRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
